/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    news: News;
    interviews: Interview;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    news: NewsSelect<false> | NewsSelect<true>;
    interviews: InterviewsSelect<false> | InterviewsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * 公開サイトの「お知らせ」（/news）に表示される記事。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * 記事のURL（/news/◯◯）になります。空のまま保存すると日付から自動で作られます。公開後の変更はリンク切れのもとになるので避けてください。
   */
  slug?: string | null;
  /**
   * 一覧に表示される日付。新しい順に並びます。
   */
  date: string;
  category: 'お知らせ' | '製品' | '採用' | 'メディア';
  blocks?:
    | (
        | {
            /**
             * **太字**、==マーカー== が使えます。改行はそのまま反映されます。
             */
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'h2';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'h3';
          }
        | {
            /**
             * 通常はこちらにアップロードしてください。
             */
            media?: (number | null) | Media;
            /**
             * 通常は上の「画像」を使用。両方ある場合は「画像」が優先されます。
             */
            src?: string | null;
            href?: string | null;
            alt?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            /**
             * YouTube/Vimeo の共有URL、または mp4 直リンク。
             */
            src: string;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            /**
             * 採用ページの該当職種のエントリーフォームへのリンクボタンになります（記事の末尾に置くのがおすすめです）。職種ID: job-dryice＝ドライアイス加工・配送スタッフ（正社員）（ドライアイスチーム） ／ job-keiri-zaimu＝経理財務（正社員）（本社） ／ job-saiyo-koho＝採用広報（正社員）（本社） ／ job-route-sales＝ルート営業スタッフ（正社員）（食品事業部） ／ job-shohin-kaihatsu＝商品開発（正社員）（西大寺工場） ／ job-jinji-romu＝人事労務（正社員）（本社） ／ job-seisan-gijutsu＝生産技術（正社員）（西大寺・二日市工場） ／ job-futsukaichi-seizo＝製造オペレーター／ラインマネージャー（正社員）（二日市工場） ／ job-hinshitsu-kanri＝品質管理（正社員）（西大寺工場） ／ job-souko＝倉庫作業スタッフ（正社員）（西大寺工場） ／ job-seizo＝製造スタッフ（正社員）（西大寺工場） ／ job-seizo-hojo-saidaiji＝製造補助スタッフ（パート）（西大寺工場） ／ job-seizo-hojo-futsukaichi＝製造補助スタッフ（パート）（二日市工場）
             */
            job: string;
            /**
             * 空欄なら「この職種にエントリーする」と表示されます。
             */
            label?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'recruitLink';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * お知らせ記事の本文中で使う画像。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * 画像の内容の説明（目の不自由な方の読み上げ・SEO用）。
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * 採用ページの「人を知る」と記事ページ（/recruit/interview/◯◯）に表示される記事。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interviews".
 */
export interface Interview {
  id: number;
  name: string;
  /**
   * 記事のURL（/recruit/interview/◯◯）になります。空のまま保存すると自動で作られます。公開後の変更はリンク切れのもとになるので避けてください。
   */
  slug?: string | null;
  /**
   * 記事の分類（例: 社員インタビュー／座談会／仕事紹介）。一覧の絞り込みと、採用ページのカードのラベルに使われます。
   */
  category: string;
  /**
   * 採用ページのカルーセルの並び順（小さい順）。同じ値は作成順。
   */
  order?: number | null;
  /**
   * 例: アイス事業部 製造｜オペレーター
   */
  role?: string | null;
  /**
   * 例: 入社5年目（任意）
   */
  years?: string | null;
  lead: string;
  subtitle?: string | null;
  /**
   * 記事ページのヒーローと「人を知る」カードに表示。通常はこちらにアップロード。
   */
  image?: (number | null) | Media;
  /**
   * 通常は上の「メイン画像」を使用。両方ある場合は「メイン画像」が優先されます。
   */
  imageSrc?: string | null;
  blocks?:
    | (
        | {
            /**
             * **太字**、==マーカー== が使えます。改行はそのまま反映されます。
             */
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'h2';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'h3';
          }
        | {
            /**
             * 通常はこちらにアップロードしてください。
             */
            media?: (number | null) | Media;
            /**
             * 通常は上の「画像」を使用。両方ある場合は「画像」が優先されます。
             */
            src?: string | null;
            href?: string | null;
            alt?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            /**
             * YouTube/Vimeo の共有URL、または mp4 直リンク。
             */
            src: string;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            /**
             * 採用ページの該当職種のエントリーフォームへのリンクボタンになります（記事の末尾に置くのがおすすめです）。職種ID: job-dryice＝ドライアイス加工・配送スタッフ（正社員）（ドライアイスチーム） ／ job-keiri-zaimu＝経理財務（正社員）（本社） ／ job-saiyo-koho＝採用広報（正社員）（本社） ／ job-route-sales＝ルート営業スタッフ（正社員）（食品事業部） ／ job-shohin-kaihatsu＝商品開発（正社員）（西大寺工場） ／ job-jinji-romu＝人事労務（正社員）（本社） ／ job-seisan-gijutsu＝生産技術（正社員）（西大寺・二日市工場） ／ job-futsukaichi-seizo＝製造オペレーター／ラインマネージャー（正社員）（二日市工場） ／ job-hinshitsu-kanri＝品質管理（正社員）（西大寺工場） ／ job-souko＝倉庫作業スタッフ（正社員）（西大寺工場） ／ job-seizo＝製造スタッフ（正社員）（西大寺工場） ／ job-seizo-hojo-saidaiji＝製造補助スタッフ（パート）（西大寺工場） ／ job-seizo-hojo-futsukaichi＝製造補助スタッフ（パート）（二日市工場）
             */
            job: string;
            /**
             * 空欄なら「この職種にエントリーする」と表示されます。
             */
            label?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'recruitLink';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 記事管理画面（/admin）にログインできるメンバー。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'interviews';
        value: number | Interview;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  category?: T;
  blocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        h2?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        h3?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              media?: T;
              src?: T;
              href?: T;
              alt?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              src?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        recruitLink?:
          | T
          | {
              job?: T;
              label?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interviews_select".
 */
export interface InterviewsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  order?: T;
  role?: T;
  years?: T;
  lead?: T;
  subtitle?: T;
  image?: T;
  imageSrc?: T;
  blocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        h2?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        h3?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              media?: T;
              src?: T;
              href?: T;
              alt?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              src?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        recruitLink?:
          | T
          | {
              job?: T;
              label?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}